const movies = [
  { title: "The Brutalist", year: 2024, director: "Brady Corbet", poster: "images/posters/the-brutalist.jpg", imdb_id: "tt8999762", imdb_rating: "7.3", rt_score: "93%" },
  { title: "One Battle After Another", year: 2025, director: "Paul Thomas Anderson", poster: "images/posters/one-battle-after-another.jpg", imdb_id: "tt30144839", imdb_rating: "7.7", rt_score: "95%" },
  { title: "Dune: Part One", year: 2021, director: "Denis Villeneuve", poster: "images/posters/dune-part-one.jpg", imdb_id: "tt1160419", imdb_rating: "8.0", rt_score: "83%" },
  { title: "Dune: Part Two", year: 2024, director: "Denis Villeneuve", poster: "images/posters/dune-part-two.jpg", imdb_id: "tt15239678", imdb_rating: "8.4", rt_score: "92%" },
  { title: "Eddington", year: 2025, director: "Ari Aster", poster: "images/posters/eddington.jpg", imdb_id: "tt31176520", imdb_rating: "6.6", rt_score: "69%" },
  { title: "The Holdovers", year: 2023, director: "Alexander Payne", poster: "images/posters/the-holdovers.jpg", imdb_id: "tt14849194", imdb_rating: "7.9", rt_score: "97%" },
  { title: "Materialists", year: 2025, director: "Celine Song", poster: "images/posters/materialists.jpg", imdb_id: "tt30253473", imdb_rating: "6.3", rt_score: "77%" },
  { title: "Sinners", year: 2025, director: "Ryan Coogler", poster: "images/posters/sinners.jpg", imdb_id: "tt31193180", imdb_rating: "7.5", rt_score: "97%" },
  { title: "Oppenheimer", year: 2023, director: "Christopher Nolan", poster: "images/posters/oppenheimer.jpg", imdb_id: "tt15398776", imdb_rating: "8.2", rt_score: "93%" },
  { title: "Interstellar", year: 2014, director: "Christopher Nolan", poster: "images/posters/interstellar.jpg", imdb_id: "tt0816692", imdb_rating: "8.7", rt_score: "73%" },
  { title: "Dunkirk", year: 2017, director: "Christopher Nolan", poster: "images/posters/dunkirk.jpg", imdb_id: "tt5013056", imdb_rating: "7.8", rt_score: "92%" },
  { title: "Catch Me If You Can", year: 2002, director: "Steven Spielberg", poster: "images/posters/catch-me-if-you-can.jpg", imdb_id: "tt0264464", imdb_rating: "8.1", rt_score: "96%" },
  { title: "Saving Private Ryan", year: 1998, director: "Steven Spielberg", poster: "images/posters/saving-private-ryan.jpg", imdb_id: "tt0120815", imdb_rating: "8.6", rt_score: "94%" },
  { title: "The Godfather", year: 1972, director: "Francis Ford Coppola", poster: "images/posters/the-godfather.jpg", imdb_id: "tt0068646", imdb_rating: "9.2", rt_score: "97%" },
  { title: "The Godfather Part II", year: 1974, director: "Francis Ford Coppola", poster: "images/posters/the-godfather-part-ii.jpg", imdb_id: "tt0071562", imdb_rating: "9.0", rt_score: "96%" },
  { title: "The Godfather Part III", year: 1990, director: "Francis Ford Coppola", poster: "images/posters/the-godfather-part-iii.jpg", imdb_id: "tt0099674", imdb_rating: "7.5", rt_score: "66%" },
  { title: "Django Unchained", year: 2012, director: "Quentin Tarantino", poster: "images/posters/django-unchained.jpg", imdb_id: "tt1853728", imdb_rating: "8.5", rt_score: "87%" },
  { title: "Pulp Fiction", year: 1994, director: "Quentin Tarantino", poster: "images/posters/pulp-fiction.jpg", imdb_id: "tt0110912", imdb_rating: "8.8", rt_score: "92%" },
  { title: "Kill Bill: Vol. 1", year: 2003, director: "Quentin Tarantino", poster: "images/posters/kill-bill-vol-1.jpg", imdb_id: "tt0266697", imdb_rating: "8.2", rt_score: "85%" },
  { title: "Kill Bill: Vol. 2", year: 2004, director: "Quentin Tarantino", poster: "images/posters/kill-bill-vol-2.jpg", imdb_id: "tt0378194", imdb_rating: "8.0", rt_score: "84%" },
  { title: "The Killer", year: 2023, director: "David Fincher", poster: "images/posters/the-killer.jpg", imdb_id: "tt1136617", imdb_rating: "6.7", rt_score: "85%" },
  { title: "Once Upon a Time in Hollywood", year: 2019, director: "Quentin Tarantino", poster: "images/posters/once-upon-a-time-in-hollywood.jpg", imdb_id: "tt7131622", imdb_rating: "7.6", rt_score: "86%" },
  { title: "Casino", year: 1995, director: "Martin Scorsese", poster: "images/posters/casino.jpg", imdb_id: "tt0112641", imdb_rating: "8.2", rt_score: "79%" },
  { title: "Inglourious Basterds", year: 2009, director: "Quentin Tarantino", poster: "images/posters/inglourious-basterds.jpg", imdb_id: "tt0361748", imdb_rating: "8.4", rt_score: "89%" },
  { title: "The Hateful Eight", year: 2015, director: "Quentin Tarantino", poster: "images/posters/the-hateful-eight.jpg", imdb_id: "tt3460252", imdb_rating: "7.8", rt_score: "74%" },
  { title: "Jackie Brown", year: 1997, director: "Quentin Tarantino", poster: "images/posters/jackie-brown.jpg", imdb_id: "tt0119396", imdb_rating: "7.5", rt_score: "88%" },
  { title: "The Martian", year: 2015, director: "Ridley Scott", poster: "images/posters/the-martian.jpg", imdb_id: "tt3659388", imdb_rating: "8.0", rt_score: "91%" },
  { title: "Anora", year: 2024, director: "Sean Baker", poster: "images/posters/anora.jpg", imdb_id: "tt28607951", imdb_rating: "7.4", rt_score: "93%" },
  { title: "The Florida Project", year: 2017, director: "Sean Baker", poster: "images/posters/the-florida-project.jpg", imdb_id: "tt5649144", imdb_rating: "7.6", rt_score: "96%" },
  { title: "Red Rocket", year: 2021, director: "Sean Baker", poster: "images/posters/red-rocket.jpg", imdb_id: "tt13453006", imdb_rating: "7.1", rt_score: "90%" },
  { title: "The Substance", year: 2024, director: "Coralie Fargeat", poster: "images/posters/the-substance.jpg", imdb_id: "tt17526714", imdb_rating: "7.2", rt_score: "89%" },
  { title: "Blow Out", year: 1981, director: "Brian De Palma", poster: "images/posters/blow-out.jpg", imdb_id: "tt0082085", imdb_rating: "7.4", rt_score: "88%" },
  { title: "Taxi Driver", year: 1976, director: "Martin Scorsese", poster: "images/posters/taxi-driver.jpg", imdb_id: "tt0075314", imdb_rating: "8.2", rt_score: "89%" },
  { title: "The Conversation", year: 1974, director: "Francis Ford Coppola", poster: "images/posters/the-conversation.jpg", imdb_id: "tt0071360", imdb_rating: "7.7", rt_score: "94%" },
  { title: "Vertigo", year: 1958, director: "Alfred Hitchcock", poster: "images/posters/vertigo.jpg", imdb_id: "tt0052357", imdb_rating: "8.2", rt_score: "93%" },
  { title: "The Matrix", year: 1999, director: "Lana Wachowski; Lilly Wachowski", poster: "images/posters/the-matrix.jpg", imdb_id: "tt0133093", imdb_rating: "8.7", rt_score: "83%" },
  { title: "Margin Call", year: 2011, director: "J. C. Chandor", poster: "images/posters/margin-call.jpg", imdb_id: "tt1615147", imdb_rating: "7.1", rt_score: "87%" },
  { title: "All the Money in the World", year: 2017, director: "Ridley Scott", poster: "images/posters/all-the-money-in-the-world.jpg", imdb_id: "tt5294550", imdb_rating: "6.8", rt_score: "79%" },
];
